// PDF Service — Invoice & Statement PDF generation using jsPDF + autoTable
// Server-only, returns Buffer for HTTP Response or file download

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { InvoiceRecord } from "~/types/invoice";
import type { InvoiceStatus } from "@prisma/client";

// ── Types ──────────────────────────────────────────────────────────────────

export interface InvoicePdfData {
  invoice: InvoiceRecord;
  customer: {
    name: string;
    company: string | null;
    email: string;
  };
  /** Optional shop/merchant info */
  shopInfo?: {
    name: string;
    address?: string;
    email?: string;
  };
}

export interface StatementPdfData {
  customer: {
    name: string;
    company: string | null;
    email: string;
    creditLimit: string;
    creditUsed: string;
    creditAvailable: string;
  };
  invoices: Array<{
    invoiceNumber: string;
    amount: string;
    currency: string;
    issueDate: string;
    dueDate: string;
    status: InvoiceStatus;
    daysOverdue: number;
  }>;
  aging: Array<{ label: string; count: number; totalAmount: string }>;
  totalOutstanding: string;
  totalOverdue: string;
  generatedDate: Date;
  shopInfo?: {
    name: string;
    address?: string;
    email?: string;
  };
}

// ── Constants ──────────────────────────────────────────────────────────────

const PAGE_MARGIN = 20;
const BRAND_COLOR: [number, number, number] = [44, 62, 80]; // dark blue-grey
const ACCENT_COLOR: [number, number, number] = [52, 152, 219]; // blue
const LIGHT_GRAY: [number, number, number] = [245, 245, 245];
const TABLE_HEAD_BG: [number, number, number] = [44, 62, 80];
const TABLE_HEAD_FG: [number, number, number] = [255, 255, 255];
const FONT_FAMILY = "helvetica";

// ── Helpers ────────────────────────────────────────────────────────────────

function formatCurrency(amount: string | number, currency: string): string {
  const num = typeof amount === "string" ? Number(amount) : amount;
  return `${currency} ${num.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDate(date: Date | string): string {
  const d = typeof date === "string" ? new Date(date) : date;
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function addHeader(doc: jsPDF, shopInfo?: InvoicePdfData["shopInfo"]): void {
  const pageWidth = doc.internal.pageSize.getWidth();

  // Company name / logo placeholder
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(22);
  doc.setTextColor(...BRAND_COLOR);
  doc.text(shopInfo?.name ?? "TruCredit", PAGE_MARGIN, 25);

  // Subtitle
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  const subtitleParts: string[] = [];
  if (shopInfo?.address) subtitleParts.push(shopInfo.address);
  if (shopInfo?.email) subtitleParts.push(shopInfo.email);
  if (subtitleParts.length > 0) {
    doc.text(subtitleParts.join(" | "), PAGE_MARGIN, 32);
  }

  // Divider line
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, 38, pageWidth - PAGE_MARGIN, 38);
}

function addFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont(FONT_FAMILY, "normal");
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    const footerY = pageHeight - 12;
    doc.text(
      `Generated by TruCredit — Page ${i} of ${pageCount}`,
      pageWidth / 2,
      footerY,
      { align: "center" },
    );
  }
}

function statusLabel(status: InvoiceStatus): string {
  const map: Record<string, string> = {
    PAID: "Paid",
    OVERDUE: "Overdue",
    DISPUTED: "Disputed",
    PARTIALLY_PAID: "Partial",
    DRAFT: "Draft",
    PENDING: "Pending",
    VOID: "Void",
  };
  return map[status] ?? status;
}

// ── Invoice PDF ────────────────────────────────────────────────────────────

/**
 * Generate a professional invoice PDF and return as Buffer.
 */
export function generateInvoicePdf(data: InvoicePdfData): Buffer {
  const { invoice, customer, shopInfo } = data;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 45;

  addHeader(doc, shopInfo);

  // ── Invoice title ──
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(26);
  doc.setTextColor(...ACCENT_COLOR);
  doc.text("INVOICE", PAGE_MARGIN, cursorY);
  cursorY += 10;

  // Invoice number
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_COLOR);
  doc.text(invoice.invoiceNumber, PAGE_MARGIN, cursorY);
  cursorY += 16;

  // ── Two-column: Bill To / Invoice Info ──
  const col1X = PAGE_MARGIN;
  const col2X = pageWidth / 2 + 5;

  // Bill To
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("BILL TO", col1X, cursorY);
  cursorY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(11);
  doc.text(customer.name, col1X, cursorY);
  cursorY += 5;
  if (customer.company) {
    doc.text(customer.company, col1X, cursorY);
    cursorY += 5;
  }
  doc.text(customer.email, col1X, cursorY);

  // Invoice Info (right column)
  const infoStartY = cursorY - (customer.company ? 10 : 5);
  const infoRows: Array<[string, string]> = [
    ["Issue Date", formatDate(invoice.issueDate)],
    ["Due Date", formatDate(invoice.dueDate)],
    ["Status", statusLabel(invoice.status)],
    ["Net Terms", `${invoice.netTermsDays} days`],
    ["Currency", invoice.currency],
    ...(invoice.paymentMethod ? [["Payment Method", invoice.paymentMethod] as [string, string]] : []),
  ];

  let infoY = infoStartY;
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("INVOICE DETAILS", col2X, infoY);
  infoY += 5;

  for (const [label, value] of infoRows) {
    doc.setFont(FONT_FAMILY, "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(label, col2X, infoY);
    doc.setTextColor(60, 60, 60);
    doc.text(value, col2X + 50, infoY);
    infoY += 5;
  }

  cursorY = Math.max(cursorY, infoY) + 12;

  // ── Line Items Table ──
  const tableBody = [
    [
      "1",
      invoice.shopifyOrderName ?? `Order for ${invoice.invoiceNumber}`,
      "",
      formatCurrency(invoice.amount, invoice.currency),
    ],
  ];

  autoTable(doc, {
    startY: cursorY,
    head: [["#", "Description", "Notes", "Amount"]],
    body: tableBody,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: {
      font: FONT_FAMILY,
      fontSize: 9.5,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: TABLE_HEAD_BG,
      textColor: TABLE_HEAD_FG,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 12, halign: "center" },
      1: { cellWidth: "auto" },
      2: { cellWidth: "auto" },
      3: { halign: "right", cellWidth: 40 },
    },
    alternateRowStyles: {
      fillColor: LIGHT_GRAY,
    },
  });

  // ── Totals ──
  const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? cursorY + 20;
  let totalsY = finalY + 8;
  const totalsX = pageWidth - PAGE_MARGIN - 80;

  doc.setDrawColor(220, 220, 220);
  doc.line(totalsX, totalsY, pageWidth - PAGE_MARGIN, totalsY);

  totalsY += 7;
  // Subtotal (same as amount since single line item)
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Subtotal", totalsX, totalsY);
  doc.text(formatCurrency(invoice.amount, invoice.currency), pageWidth - PAGE_MARGIN, totalsY, { align: "right" });

  totalsY += 6;
  doc.text("Tax (0%)", totalsX, totalsY);
  doc.text(formatCurrency(0, invoice.currency), pageWidth - PAGE_MARGIN, totalsY, { align: "right" });

  totalsY += 8;
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(0.5);
  doc.line(totalsX, totalsY, pageWidth - PAGE_MARGIN, totalsY);

  totalsY += 8;
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Total Due", totalsX, totalsY);
  doc.text(formatCurrency(invoice.amount, invoice.currency), pageWidth - PAGE_MARGIN, totalsY, { align: "right" });

  // ── Payment Terms ──
  totalsY += 16;
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("PAYMENT TERMS", PAGE_MARGIN, totalsY);
  totalsY += 6;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.text(`Net ${invoice.netTermsDays} days from invoice date.`, PAGE_MARGIN, totalsY);
  totalsY += 5;
  doc.text("Please include the invoice number with your payment.", PAGE_MARGIN, totalsY);

  // ── Footer ──
  addFooter(doc);

  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}

// ── Statement PDF ──────────────────────────────────────────────────────────

/**
 * Generate a customer account statement PDF and return as Buffer.
 */
export function generateStatementPdf(data: StatementPdfData): Buffer {
  const { customer, invoices, aging, totalOutstanding, totalOverdue, generatedDate, shopInfo } = data;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let cursorY = 45;

  addHeader(doc, shopInfo);

  // ── Statement title ──
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(22);
  doc.setTextColor(...ACCENT_COLOR);
  doc.text("ACCOUNT STATEMENT", PAGE_MARGIN, cursorY);
  cursorY += 16;

  // ── Customer Info + Statement Date ──
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("PREPARED FOR", PAGE_MARGIN, cursorY);
  cursorY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  doc.text(customer.name, PAGE_MARGIN, cursorY);
  cursorY += 5;
  if (customer.company) {
    doc.text(customer.company, PAGE_MARGIN, cursorY);
    cursorY += 5;
  }
  doc.setFontSize(10);
  doc.text(customer.email, PAGE_MARGIN, cursorY);

  // Statement date + credit info (right column)
  const rightX = pageWidth / 2 + 5;
  let rightY = cursorY - (customer.company ? 13 : 8);

  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("STATEMENT DATE", rightX, rightY);
  rightY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(formatDate(generatedDate), rightX, rightY);
  rightY += 8;

  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("CREDIT LIMIT", rightX, rightY);
  rightY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(formatCurrency(customer.creditLimit, "USD"), rightX, rightY);
  rightY += 8;

  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("CREDIT USED", rightX, rightY);
  rightY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(formatCurrency(customer.creditUsed, "USD"), rightX, rightY);
  rightY += 8;

  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(9);
  doc.setTextColor(128, 128, 128);
  doc.text("CREDIT AVAILABLE", rightX, rightY);
  rightY += 5;
  doc.setFont(FONT_FAMILY, "normal");
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.text(formatCurrency(customer.creditAvailable, "USD"), rightX, rightY);

  cursorY = Math.max(cursorY, rightY) + 10;

  // ── Summary Box ──
  const boxY = cursorY;
  const boxH = 20;
  doc.setFillColor(240, 248, 255);
  doc.rect(PAGE_MARGIN, boxY, pageWidth - PAGE_MARGIN * 2, boxH, "F");

  const summaryItems = [
    { label: "Total Outstanding", value: formatCurrency(totalOutstanding, "USD"), x: PAGE_MARGIN + 8 },
    { label: "Total Overdue", value: formatCurrency(totalOverdue, "USD"), x: pageWidth / 2 - 20 },
    { label: "Invoice Count", value: String(invoices.length), x: pageWidth - PAGE_MARGIN - 60 },
  ];

  for (const item of summaryItems) {
    doc.setFont(FONT_FAMILY, "bold");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(item.label, item.x, boxY + 8);
    doc.setFont(FONT_FAMILY, "bold");
    doc.setFontSize(13);
    doc.setTextColor(...BRAND_COLOR);
    doc.text(item.value, item.x, boxY + 16);
  }

  cursorY = boxY + boxH + 10;

  // ── Aging Summary Table ──
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Aging Summary", PAGE_MARGIN, cursorY);
  cursorY += 8;

  const agingBody = aging.map((bucket) => [
    bucket.label,
    String(bucket.count),
    formatCurrency(bucket.totalAmount, "USD"),
  ]);

  autoTable(doc, {
    startY: cursorY,
    head: [["Aging Bucket", "Count", "Amount"]],
    body: agingBody,
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
    styles: {
      font: FONT_FAMILY,
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: TABLE_HEAD_BG,
      textColor: TABLE_HEAD_FG,
      fontStyle: "bold",
    },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 30, halign: "center" },
      2: { halign: "right", cellWidth: 40 },
    },
    alternateRowStyles: {
      fillColor: LIGHT_GRAY,
    },
  });

  cursorY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? cursorY + 20;
  cursorY += 8;

  // ── Outstanding Invoices Table ──
  doc.setFont(FONT_FAMILY, "bold");
  doc.setFontSize(12);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("Outstanding Invoices", PAGE_MARGIN, cursorY);
  cursorY += 8;

  if (invoices.length === 0) {
    doc.setFont(FONT_FAMILY, "normal");
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text("No outstanding invoices.", PAGE_MARGIN, cursorY);
  } else {
    const invoiceBody = invoices.map((inv) => [
      inv.invoiceNumber,
      formatDate(inv.issueDate),
      formatDate(inv.dueDate),
      String(inv.daysOverdue),
      statusLabel(inv.status),
      formatCurrency(inv.amount, inv.currency),
    ]);

    autoTable(doc, {
      startY: cursorY,
      head: [["Invoice #", "Issue Date", "Due Date", "Days Overdue", "Status", "Amount"]],
      body: invoiceBody,
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      styles: {
        font: FONT_FAMILY,
        fontSize: 8.5,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: TABLE_HEAD_BG,
        textColor: TABLE_HEAD_FG,
        fontStyle: "bold",
      },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 32 },
        2: { cellWidth: 32 },
        3: { cellWidth: 28, halign: "center" },
        4: { cellWidth: 22, halign: "center" },
        5: { halign: "right", cellWidth: 38 },
      },
      alternateRowStyles: {
        fillColor: LIGHT_GRAY,
      },
      didDrawPage: () => {
        // Repeat table header on new pages (handled automatically by autoTable)
      },
    });
  }

  // ── Footer ──
  addFooter(doc);

  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}
