import type { MetaFunction } from "@remix-run/node";
import { useRouteError } from "@remix-run/react";

export const meta: MetaFunction = () => [
  { title: "Privacy Policy — TruCredit" },
];

export function ErrorBoundary() {
  const error = useRouteError();
  const msg = error instanceof Error ? error.message : "An unexpected error occurred.";
  return (
    <PageShell title="Privacy Policy">
      <div style={styles.alert}>
        Failed to load Privacy Policy: {msg}
      </div>
    </PageShell>
  );
}

export default function PrivacyPolicy() {
  return (
    <PageShell title="Privacy Policy" subtitle="Last Updated: July 22, 2026">
      <Section title="1. Introduction">
        <P>
          This Privacy Policy describes how TruCredit (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) collects,
          uses, and shares information when you install and use the TruCredit application (the
          &quot;App&quot;) through the Shopify platform.
        </P>
        <P>
          By installing TruCredit, you (&quot;Merchant&quot;) agree to the collection and use of
          information as described in this policy. We are committed to protecting your data and
          operating in compliance with applicable privacy laws including the General Data Protection
          Regulation (GDPR), California Consumer Privacy Act (CCPA), and other relevant data
          protection legislation.
        </P>
      </Section>

      <Section title="2. Information We Collect">
        <Subsection title="2.1 Information from Merchants (You)">
          <P>When you install and use TruCredit, we collect:</P>
          <Ul>
            <Li><Strong>Account Information</Strong> — Shop domain, email address, name, for app authentication and communication</Li>
            <Li><Strong>Store Configuration</Strong> — Currency, timezone, preferences, to customize app functionality</Li>
            <Li><Strong>Subscription Details</Strong> — Plan tier, billing status, to manage your subscription</Li>
          </Ul>
        </Subsection>
        <Subsection title="2.2 Information from Your Customers (B2B Buyers)">
          <P>Through the Shopify Admin API, we access the following customer data on your behalf:</P>
          <Ul>
            <Li><Strong>Contact Information</Strong> — Name, email, phone number, to send payment reminders and collection communications</Li>
            <Li><Strong>Company Information</Strong> — Company name, billing address, to associate contacts with B2B credit profiles</Li>
            <Li><Strong>Order &amp; Payment History</Strong> — Order amounts, payment dates, financial status, to calculate credit scores and manage accounts receivable</Li>
            <Li><Strong>Payment Terms</Strong> — Net 30/60/90 settings, to determine invoice due dates</Li>
          </Ul>
        </Subsection>
        <Subsection title="2.3 Information Generated by the App">
          <Ul>
            <Li><Strong>Credit Profiles</Strong> — Credit score, credit grade, credit limit, usage, to manage B2B credit limits</Li>
            <Li><Strong>Collection Records</Strong> — Email send dates, reply content, task status, to track collection activities</Li>
            <Li><Strong>AI-Generated Content</Strong> — Collection email drafts, intent classifications, to automate communications</Li>
            <Li><Strong>Analytics</Strong> — AR aging data, payment patterns, to provide dashboard insights</Li>
          </Ul>
        </Subsection>
        <Subsection title="2.4 Technical Information">
          <Ul>
            <Li><Strong>Log Data</Strong> — API call timestamps, error logs, for troubleshooting and service reliability</Li>
            <Li><Strong>Session Data</Strong> — Authentication tokens, to maintain secure sessions</Li>
          </Ul>
        </Subsection>
      </Section>

      <Section title="3. How We Use Your Information">
        <P>We use the collected information solely to provide and improve the TruCredit service:</P>
        <Ul>
          <Li><Strong>Credit Management</Strong> — Assess customer creditworthiness, set and enforce credit limits, and prevent over-limit orders at checkout.</Li>
          <Li><Strong>Automated Collections</Strong> — Send payment reminder emails on your behalf when invoices become due or overdue.</Li>
          <Li><Strong>AI Processing</Strong> — Generate collection email content with appropriate tone levels; classify customer reply intents (e.g., &quot;will pay&quot;, &quot;dispute&quot;, &quot;payment plan request&quot;).</Li>
          <Li><Strong>Analytics &amp; Reporting</Strong> — Provide AR aging dashboards, payment pattern insights, and cash flow visibility.</Li>
          <Li><Strong>Service Operation</Strong> — Authenticate your session, process webhooks, sync data with Shopify, and maintain service reliability.</Li>
          <Li><Strong>Communication</Strong> — Send you service-related notifications (e.g., onboarding guides, critical alerts, feature updates).</Li>
        </Ul>
      </Section>

      <Section title="4. AI &amp; Data Processing">
        <P>TruCredit uses AI (powered by DeepSeek) for the following purposes:</P>
        <Ul>
          <Li><Strong>Collection Email Generation</Strong> — Input: Invoice amount, customer name, overdue days, tone level. Output: Draft email content. Only anonymized context is sent to the AI provider; no raw PII.</Li>
          <Li><Strong>Reply Intent Classification</Strong> — Input: Customer reply text. Output: Intent category (7 types). Reply text content is sent to the AI provider.</Li>
          <Li><Strong>Credit Score Calculation</Strong> — Input: Order history patterns, payment timing. Output: Numeric score (0-100). Only aggregated behavioral patterns are sent to the AI provider.</Li>
        </Ul>
        <P><Strong>Important:</Strong></P>
        <Ul>
          <Li>We do NOT use merchant or customer data to train AI models.</Li>
          <Li>AI processing is performed per-request; data is not retained by the AI provider after processing.</Li>
          <Li>You can disable AI features and use manual templates instead.</Li>
        </Ul>
      </Section>

      <Section title="5. How We Share Your Information">
        <P>We do NOT sell, rent, or trade your data or your customers&apos; data to third parties.</P>
        <P>We share data only with the following service providers, strictly for operating the App:</P>
        <Ul>
          <Li><Strong>Shopify</Strong> — Platform (API, webhooks, billing). Data shared as required by Shopify App integration.</Li>
          <Li><Strong>Amazon Web Services (AWS SES)</Strong> — Send collection emails on your behalf. Data shared: recipient email, email content.</Li>
          <Li><Strong>DeepSeek</Strong> — AI text generation and classification. Data shared: anonymized context, reply text.</Li>
          <Li><Strong>Railway</Strong> — Application hosting. All data encrypted in transit and at rest.</Li>
        </Ul>
        <P>All service providers are bound by data processing agreements and process data solely on our instructions.</P>
      </Section>

      <Section title="6. Data Retention">
        <Ul>
          <Li><Strong>Merchant Account Data</Strong> — Retained for duration of app installation plus 30 days. Deleted upon app uninstall.</Li>
          <Li><Strong>Customer Credit Profiles</Strong> — Retained for duration of app installation. Deleted upon app uninstall.</Li>
          <Li><Strong>Collection History &amp; Events</Strong> — Retained for duration of app installation. Deleted upon app uninstall.</Li>
          <Li><Strong>Invoice Records</Strong> — Retained for duration of app installation. Deleted upon app uninstall.</Li>
          <Li><Strong>Technical Logs</Strong> — Retained for 90 days. Automatic rotation.</Li>
        </Ul>
        <P>
          When you uninstall TruCredit, we delete all your data and your customers&apos; data within
          30 days. This process is triggered automatically via Shopify&apos;s <code>APP_UNINSTALLED</code> webhook.
        </P>
      </Section>

      <Section title="7. Data Security">
        <P>We implement appropriate technical and organizational measures to protect your data:</P>
        <Ul>
          <Li><Strong>Encryption in Transit</Strong> — All data transmitted via HTTPS/TLS 1.3.</Li>
          <Li><Strong>Encryption at Rest</Strong> — Database encrypted at rest (AES-256).</Li>
          <Li><Strong>Access Control</Strong> — Data isolated per shop (all queries filtered by <code>shopId</code>); no cross-merchant data access.</Li>
          <Li><Strong>Authentication</Strong> — Shopify OAuth 2.0 for merchant sessions; HMAC signature verification for all webhooks and public API endpoints.</Li>
          <Li><Strong>Infrastructure</Strong> — Hosted on SOC 2 compliant infrastructure.</Li>
          <Li><Strong>Minimal Data Access</Strong> — We request only the Shopify API scopes necessary for app functionality.</Li>
        </Ul>
      </Section>

      <Section title="8. Your Rights (GDPR &amp; CCPA)">
        <Subsection title="For Merchants:">
          <P>You have the right to:</P>
          <Ul>
            <Li><Strong>Access</Strong> — Request a copy of all data we hold about you and your customers.</Li>
            <Li><Strong>Rectification</Strong> — Request correction of inaccurate data.</Li>
            <Li><Strong>Deletion</Strong> — Request deletion of all data (also triggered automatically on uninstall).</Li>
            <Li><Strong>Portability</Strong> — Request your data in a machine-readable format.</Li>
            <Li><Strong>Restriction</Strong> — Request we stop processing your data while a complaint is investigated.</Li>
            <Li><Strong>Objection</Strong> — Object to specific data processing activities.</Li>
          </Ul>
        </Subsection>
        <Subsection title="For Your Customers (B2B Buyers):">
          <P>
            Your customers&apos; data is processed on your behalf (you are the Data Controller; we are
            the Data Processor). If a customer contacts us directly with a data request, we will
            refer them to you.
          </P>
        </Subsection>
        <Subsection title="How to Exercise These Rights:">
          <P>
            Contact us at{" "}
            <Strong><A href={`mailto:${process.env.SUPPORT_EMAIL || "basekit.studio@gmail.com"}`}>basekit.studio@gmail.com</A></Strong>
            {" "}or use the data request features within the App settings.
          </P>
          <P>We respond to all data requests within 30 days.</P>
        </Subsection>
      </Section>

      <Section title="9. Shopify Compliance Webhooks">
        <P>We implement all mandatory Shopify compliance webhooks:</P>
        <Ul>
          <Li><code>customers/data_request</code> — Export and provide all data held for the specified customer.</Li>
          <Li><code>customers/redact</code> — Permanently delete all data for the specified customer.</Li>
          <Li><code>shop/redact</code> — Permanently delete all data for the entire shop (48 hours after uninstall).</Li>
        </Ul>
      </Section>

      <Section title="10. Cookies &amp; Tracking">
        <P>
          TruCredit does <Strong>not</Strong> use cookies, tracking pixels, or analytics tools to
          track merchants or their customers. The App operates entirely within the Shopify Admin
          embedded interface and does not inject any tracking code into your storefront.
        </P>
      </Section>

      <Section title="11. Children&apos;s Privacy">
        <P>
          TruCredit is a B2B business tool and is not directed at individuals under 16 years of age.
          We do not knowingly collect personal information from children.
        </P>
      </Section>

      <Section title="12. International Data Transfers">
        <P>
          Your data may be processed in data centers located in the United States. Where data is
          transferred outside your jurisdiction, we ensure appropriate safeguards are in place (e.g.,
          Standard Contractual Clauses for EU data transfers).
        </P>
      </Section>

      <Section title="13. Changes to This Policy">
        <P>
          We may update this Privacy Policy from time to time. When we make material changes, we will
          notify you via the App or by email. The &quot;Last Updated&quot; date at the top indicates
          when the policy was last revised.
        </P>
      </Section>

      <Section title="14. Contact Us">
        <P>If you have any questions about this Privacy Policy or our data practices, please contact us:</P>
        <Ul>
          <Li><Strong>Email</Strong>:{" "}<A href={`mailto:${process.env.SUPPORT_EMAIL || "basekit.studio@gmail.com"}`}>basekit.studio@gmail.com</A></Li>
          <Li><Strong>Website</Strong>:{" "}<A href="https://trucredit-app-production.up.railway.app/privacy">https://trucredit-app-production.up.railway.app/privacy</A></Li>
          <Li><Strong>Response time</Strong>: We aim to respond to all inquiries within 24 hours.</Li>
        </Ul>
      </Section>
    </PageShell>
  );
}

// ─── Plain HTML Components (no Polaris dependency) ───

function PageShell({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div style={{ fontFamily: "Inter, -apple-system, sans-serif", background: "#f6f6f7", color: "#202223", minHeight: "100vh", padding: 0, margin: 0 }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px" }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, margin: "0 0 4px" }}>{title}</h1>
        {subtitle && <p style={{ fontSize: 14, color: "#6d7175", margin: "0 0 32px" }}>{subtitle}</p>}
        <div style={styles.card}>{children}</div>
        <p style={{ textAlign: "center", fontSize: 13, color: "#999", marginTop: 32 }}>
          &copy; {new Date().getFullYear()} TruCredit. All rights reserved.
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 12px", color: "#1a1a2e" }}>{title}</h2>
      {children}
    </div>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <h3 style={{ fontSize: 15, fontWeight: 600, margin: "0 0 8px", color: "#333" }}>{title}</h3>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 14, lineHeight: 1.7, color: "#4a4a4a", margin: "0 0 12px" }}>{children}</p>;
}

function Strong({ children }: { children: React.ReactNode }) {
  return <strong style={{ fontWeight: 600 }}>{children}</strong>;
}

function Ul({ children }: { children: React.ReactNode }) {
  return <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>{children}</ul>;
}

function Li({ children }: { children: React.ReactNode }) {
  return <li style={{ fontSize: 14, lineHeight: 1.8, color: "#4a4a4a", marginBottom: 4 }}>{children}</li>;
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} style={{ color: "#008060", textDecoration: "none" }}>{children}</a>;
}

const styles = {
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: 40,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  alert: {
    background: "#FFF4E5",
    borderRadius: 8,
    padding: 16,
    fontSize: 14,
    color: "#B98900",
  },
};
