import type { MetaFunction } from "@remix-run/node";
import { useRouteError } from "@remix-run/react";

export const meta: MetaFunction = () => [
  { title: "Terms of Service — TruCredit" },
];

export function ErrorBoundary() {
  const error = useRouteError();
  const msg = error instanceof Error ? error.message : "An unexpected error occurred.";
  return (
    <PageShell title="Terms of Service">
      <div style={s.alert}>
        Failed to load Terms of Service: {msg}
      </div>
    </PageShell>
  );
}

export default function TermsOfService() {
  return (
    <PageShell title="Terms of Service" subtitle="Last updated: July 21, 2026">
      <Section title="1. Acceptance of Terms">
        <P>
          By installing, accessing, or using TruCredit (the &quot;App&quot;), you agree
          to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree
          to these Terms, do not install or use the App.
        </P>
      </Section>

      <Section title="2. Service Description">
        <P>TruCredit is a Shopify application that:</P>
        <Ul>
          <Li>Enables B2B merchants to offer net terms credit to wholesale customers</Li>
          <Li>Manages customer credit limits, credit scores, and credit grades</Li>
          <Li>Generates and manages invoices for net terms orders</Li>
          <Li>Automates accounts receivable collections with staged email reminders</Li>
          <Li>Generates AI-powered collection email content via DeepSeek AI</Li>
          <Li>Blocks Shopify checkout for customers exceeding their credit limit</Li>
          <Li>Displays AR aging reports and collection dashboards</Li>
          <Li>Supports customizable email templates and collection rule configurations</Li>
        </Ul>
      </Section>

      <Section title="3. Eligibility">
        <P>To use the App, you must:</P>
        <Ul>
          <Li>Have an active Shopify store with a valid subscription</Li>
          <Li>Have the authority to install applications on your Shopify store</Li>
          <Li>Be at least 18 years of age or the age of majority in your jurisdiction</Li>
          <Li>Comply with all applicable laws and regulations</Li>
        </Ul>
      </Section>

      <Section title="4. Account and Access">
        <Ul>
          <Li>Access to the App is granted through Shopify&apos;s OAuth authentication</Li>
          <Li>You are responsible for maintaining the security of your Shopify account</Li>
          <Li>You must not share access credentials or allow unauthorized use of the App through your account</Li>
        </Ul>
      </Section>

      <Section title="5. Acceptable Use">
        <P>You agree NOT to:</P>
        <Ul>
          <Li>Use the App to generate misleading, false, or fraudulent credit information</Li>
          <Li>Use the App to send collection emails that violate applicable debt collection laws (including the Fair Debt Collection Practices Act where applicable)</Li>
          <Li>Use the App to create content that violates any applicable laws or regulations</Li>
          <Li>Attempt to reverse-engineer, decompile, or extract our credit scoring algorithms or proprietary methods</Li>
          <Li>Use the App in any way that violates Shopify&apos;s Terms of Service or Acceptable Use Policy</Li>
          <Li>Exceed reasonable usage limits or attempt to abuse API access</Li>
          <Li>Resell, sublicense, or redistribute the App or its outputs to third parties</Li>
        </Ul>
      </Section>

      <Section title="6. AI-Generated Content">
        <Ul>
          <Li>Collection email content is generated by artificial intelligence (DeepSeek AI)</Li>
          <Li><Strong>You are solely responsible</Strong> for reviewing all AI-generated email content before it is sent to your customers</Li>
          <Li>We do not guarantee that AI-generated content is accurate, legally compliant, or free from errors</Li>
          <Li>You must ensure all AI-generated collection communications comply with applicable laws, including debt collection regulations in your jurisdiction</Li>
          <Li>We do not guarantee that AI-generated emails will result in collection of outstanding payments</Li>
        </Ul>
      </Section>

      <Section title="7. Credit Operations Disclaimer">
        <P><Strong>Important:</Strong></P>
        <Ul>
          <Li>Credit scores, grades, and limits provided by the App are calculated assessments based on configurable rules and historical data</Li>
          <Li>These assessments are not credit ratings as defined by financial regulatory bodies</Li>
          <Li>You are responsible for setting appropriate credit rules and limits based on your own risk assessment</Li>
          <Li>We are not liable for credit losses resulting from credit decisions made using the App</Li>
          <Li>You should independently verify customer creditworthiness before extending significant credit</Li>
        </Ul>
      </Section>

      <Section title="8. Pricing and Billing">
        <Ul>
          <Li>All billing is processed through Shopify&apos;s native billing system</Li>
          <Li>Subscription charges are recurring on a monthly or annual basis</Li>
          <Li>You may view current pricing within the App or on our Shopify App Store listing</Li>
          <Li>Price changes will be communicated in advance; continued use constitutes acceptance</Li>
          <Li>You may cancel your subscription at any time through your Shopify admin panel</Li>
          <Li>No refunds are provided for partial billing periods after cancellation</Li>
        </Ul>
        <P><Strong>Free Plan:</Strong></P>
        <Ul>
          <Li>The free plan provides limited functionality as described in the App</Li>
          <Li>We reserve the right to modify free plan features with reasonable notice</Li>
        </Ul>
      </Section>

      <Section title="9. Intellectual Property">
        <Ul>
          <Li>The App, including its credit scoring algorithms, collection engine methodology, interface design, and documentation, is our proprietary property</Li>
          <Li>You retain full ownership of your customer data, credit rules, email templates, and collection configurations</Li>
          <Li>AI-generated email content becomes your property once you approve and send it</Li>
          <Li>You grant us a limited license to process your data solely for the purpose of providing the service</Li>
        </Ul>
      </Section>

      <Section title="10. Service Availability">
        <Ul>
          <Li>We strive to maintain 99% uptime but do not guarantee uninterrupted service</Li>
          <Li>We may perform maintenance that temporarily affects availability</Li>
          <Li>We are not liable for downtime caused by Shopify platform issues, third-party API outages (DeepSeek, AWS SES), or circumstances beyond our control</Li>
          <Li>We reserve the right to modify, suspend, or discontinue any feature with reasonable notice</Li>
        </Ul>
      </Section>

      <Section title="11. Limitation of Liability">
        <P>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</P>
        <Ul>
          <Li>The App is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any kind, express or implied</Li>
          <Li>We disclaim all warranties including merchantability, fitness for a particular purpose, and non-infringement</Li>
          <Li>We are not liable for any indirect, incidental, special, consequential, or punitive damages</Li>
          <Li>Our total aggregate liability shall not exceed the amount you paid to us in the twelve (12) months preceding the claim</Li>
          <Li>We are not responsible for any loss of revenue, data, customer relationships, or business opportunities arising from use of the App</Li>
          <Li>We are not liable for financial losses resulting from credit decisions, collection failures, or checkout blocking actions performed by the App</Li>
        </Ul>
      </Section>

      <Section title="12. Indemnification">
        <P>
          You agree to indemnify and hold us harmless from any claims, damages, or expenses arising from:
        </P>
        <Ul>
          <Li>Your use of the App</Li>
          <Li>Credit decisions made using the App&apos;s assessments</Li>
          <Li>Collection emails sent through the App</Li>
          <Li>Your violation of these Terms</Li>
          <Li>Your violation of any applicable law (including debt collection laws) or third-party rights</Li>
        </Ul>
      </Section>

      <Section title="13. Termination">
        <Ul>
          <Li><Strong>By you</Strong>: You may uninstall the App at any time through your Shopify admin. This terminates your access immediately.</Li>
          <Li><Strong>By us</Strong>: We may suspend or terminate your access if you violate these Terms, abuse the service, or engage in activity that harms other users or our infrastructure.</Li>
          <Li><Strong>Effect of termination</Strong>: Upon termination, your data will be handled according to our Privacy Policy (deleted within 30 days).</Li>
        </Ul>
      </Section>

      <Section title="14. Modifications to Terms">
        <P>
          We reserve the right to modify these Terms at any time. Material changes will be communicated
          through the App or via email. Your continued use of the App after changes take effect constitutes
          acceptance of the revised Terms.
        </P>
      </Section>

      <Section title="15. Governing Law">
        <P>
          These Terms shall be governed by and construed in accordance with the laws of the State of Delaware,
          United States, without regard to conflict of law principles.
        </P>
      </Section>

      <Section title="16. Severability">
        <P>
          If any provision of these Terms is found to be unenforceable, the remaining provisions
          shall continue in full force and effect.
        </P>
      </Section>

      <Section title="17. Entire Agreement">
        <P>
          These Terms, together with our Privacy Policy, constitute the entire agreement between you
          and us regarding the use of the App.
        </P>
      </Section>

      <Section title="18. Contact">
        <P>For questions about these Terms:</P>
        <P><Strong>Email</Strong>:{" "}<A href={`mailto:${process.env.SUPPORT_EMAIL || "basekit.studio@gmail.com"}`}>{process.env.SUPPORT_EMAIL || "basekit.studio@gmail.com"}</A></P>
      </Section>
    </PageShell>
  );
}

// ─── Shared Plain HTML Components ───

function PageShell({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) {
  return (
    <div style={{ fontFamily: "Inter, -apple-system, sans-serif", background: "#f6f6f7", color: "#202223", minHeight: "100vh", padding: 0, margin: 0 }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px" }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, margin: "0 0 4px" }}>{title}</h1>
        {subtitle && <p style={{ fontSize: 14, color: "#6d7175", margin: "0 0 32px" }}>{subtitle}</p>}
        <div style={s.card}>{children}</div>
        <p style={{ textAlign: "center", fontSize: 13, color: "#999", marginTop: 32 }}>
          &copy; {new Date().getFullYear()} TruCredit. All rights reserved.
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontSize: 18, fontWeight: 600, margin: "0 0 12px", color: "#1a1a2e" }}>{title}</h2>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 14, lineHeight: 1.7, color: "#4a4a4a", margin: "0 0 12px" }}>{children}</p>;
}

function Strong({ children }: { children: React.ReactNode }) {
  return <strong style={{ fontWeight: 600 }}>{children}</strong>;
}

function Ul({ children }: { children: React.ReactNode }) {
  return <ul style={{ margin: "8px 0 16px", paddingLeft: 20 }}>{children}</ul>;
}

function Li({ children }: { children: React.ReactNode }) {
  return <li style={{ fontSize: 14, lineHeight: 1.8, color: "#4a4a4a", marginBottom: 4 }}>{children}</li>;
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} style={{ color: "#008060", textDecoration: "none" }}>{children}</a>;
}

const s = {
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: 40,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  alert: {
    background: "#FFF4E5",
    borderRadius: 8,
    padding: 16,
    fontSize: 14,
    color: "#B98900",
  },
};
